# Generated by Django 3.0.8 on 2020-07-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryption',
            name='identifier',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
