# Generated by Django 3.0.8 on 2020-08-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='default_key',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
