# Generated by Django 3.0.8 on 2020-07-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_encryption_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='identifier',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='ciphertext',
            field=models.BinaryField(),
        ),
    ]
