# Generated by Django 3.0.8 on 2020-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20200731_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryption',
            name='identifier',
        ),
        migrations.AddField(
            model_name='message',
            name='identifier',
            field=models.BinaryField(default=b"default"),
            preserve_default=False,
        ),
    ]
